# Services configuration
services:
  broker:
    name: broker-service
    image: pabhi4881/gomicrohub-broker-service
    tag: latest
    port: 8080
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

  authentication:
    name: authentication-service
    image: pabhi4881/gomicrohub-authentication-service
    tag: latest
    port: 8081
    replicas: 1
    env:
      - name: DSN
        value: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"

  logger:
    name: logger-service
    image: pabhi4881/gomicrohub-logger-service
    tag: latest
    port: 8082
    replicas: 1
    additionalPorts:
      - port: 5001
        name: rpc
      - port: 50001
        name: grpc

  mailer:
    name: mailer-service
    image: pabhi4881/gomicrohub-mailer-service
    tag: latest
    port: 8083
    replicas: 1
    env:
      - name: MAIL_DOMAIN
        value: ""
      - name: MAIL_HOST
        value: "localhost"
      - name: MAIL_PORT
        value: "1025"
      - name: MAIL_ENCRYPTION
        value: "none"
      - name: MAIL_USERNAME
        value: ""
      - name: MAIL_PASSWORD
        value: ""
      - name: FROM_NAME
        value: "John Smith"
      - name: FROM_ADDRESS
        value: "admin@example.com"

  listener:
    name: listener-service
    image: pabhi4881/gomicrohub-lister-services
    tag: latest
    port: 8084
    replicas: 1

  frontend:
    name: frontend-service
    image: pabhi4881/gomicrohub-frontend-service
    tag: latest
    port: 80
    replicas: 1

# Database configurations
databases:
  postgres:
    name: postgres
    image: postgres
    tag: latest
    port: 5432
    clusterIP: None
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "password"
      - name: POSTGRES_DB
        value: "users"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

  mongo:
    name: mongo
    image: mongo
    tag: 4.2.17-bionic
    port: 27017
    env:
      - name: MONGO_INITDB_DATABASE
        value: "logs"
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "admin"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "password"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

  rabbitmq:
    name: rabbitmq
    image: rabbitmq
    tag: 3.9-alpine
    port: 5672
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

  mailhog:
    name: mailhog
    image: mailhog/mailhog
    tag: latest
    ports:
      - port: 1025
        name: smtp
      - port: 8025
        name: web
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"