// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: logs.proto

package logs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogServices_WriteLogs_FullMethodName = "/logs.LogServices/WriteLogs"
)

// LogServicesClient is the client API for LogServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogServicesClient interface {
	WriteLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error)
}

type logServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewLogServicesClient(cc grpc.ClientConnInterface) LogServicesClient {
	return &logServicesClient{cc}
}

func (c *logServicesClient) WriteLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, LogServices_WriteLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServicesServer is the server API for LogServices service.
// All implementations must embed UnimplementedLogServicesServer
// for forward compatibility.
type LogServicesServer interface {
	WriteLogs(context.Context, *LogRequest) (*LogResponse, error)
	mustEmbedUnimplementedLogServicesServer()
}

// UnimplementedLogServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServicesServer struct{}

func (UnimplementedLogServicesServer) WriteLogs(context.Context, *LogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteLogs not implemented")
}
func (UnimplementedLogServicesServer) mustEmbedUnimplementedLogServicesServer() {}
func (UnimplementedLogServicesServer) testEmbeddedByValue()                     {}

// UnsafeLogServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServicesServer will
// result in compilation errors.
type UnsafeLogServicesServer interface {
	mustEmbedUnimplementedLogServicesServer()
}

func RegisterLogServicesServer(s grpc.ServiceRegistrar, srv LogServicesServer) {
	// If the following call pancis, it indicates UnimplementedLogServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogServices_ServiceDesc, srv)
}

func _LogServices_WriteLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServicesServer).WriteLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogServices_WriteLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServicesServer).WriteLogs(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LogServices_ServiceDesc is the grpc.ServiceDesc for LogServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logs.LogServices",
	HandlerType: (*LogServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteLogs",
			Handler:    _LogServices_WriteLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logs.proto",
}
