version: '3'

services:

  broker-services:
    build:
      context: ./../broker-service
      dockerfile: broker-service.dockerfile    
    ports:
    - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
