apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config
data:
  MAIL_DOMAIN: "localhost"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_ENCRYPTION: "none"
  FROM_NAME: "sanjay gupta"
  FROM_ADDRESS: "sanjaygupta07054@gmail.com"