apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 9090
          
          - path: /broker
            pathType: Prefix
            backend:
              service:
                name: broker-service
                port:
                  number: 8080

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: authentication-service
                port:
                  number: 8081

          - path: /log
            pathType: Prefix
            backend:
              service:
                name: logger-service
                port:
                  number: 8082

          - path: /mail
            pathType: Prefix
            backend:
              service:
                name: mailer-service
                port:
                  number: 8083

          - path: /mailhog
            pathType: Prefix
            backend:
              service:
                name: mailhog
                port:
                  number: 8025