apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}-logger
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: logger
spec:
  type: {{ .Values.service.loggerService.type }}
  ports:
    - port: {{ .Values.service.loggerService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: logger