apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helm-chart.fullname" . }}-mongodb
spec:
  serviceName: {{ include "helm-chart.fullname" . }}-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:{{ .Values.mongodb.image.tag }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.auth.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.auth.password }}
            - name: MONGO_INITDB_DATABASE
              value: {{ .Values.mongodb.auth.database }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}-mongodb 