apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
  MAIL_USERNAME: {{ .Values.mail.username | default "" | b64enc }}
  MAIL_PASSWORD: {{ .Values.mail.password | default "" | b64enc }}