apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pabhi18/GoMicroHub.git
    path: helm-chart
    targetRevision: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
    syncPolicy:
    automated:
      prune: true
      selfHeal: true
