name: gomicrohub

on:
  push:
    branches:
      - "main"
      - "deploy"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Build Docker image
        run: docker compose -f infra/docker-compose.yml build

      - name: Push image to Docker Hub
        run: docker compose -f infra/docker-compose.yml push
